export interface PaletteColor {
  name: string
  hex: string
}

export type CustomKind = 'search' | 'slider' | 'input' | 'swap' | 'swatches'

export interface SiteSpec {
  palette: {
    primary: PaletteColor
    secondary: PaletteColor
    tertiary: PaletteColor
    neutral: PaletteColor
  }
  fonts: {
    headline: string
    body: string
    label: string
  }
  custom: {
    kind: CustomKind
    placeholder?: string
    label?: string
  }
}

export interface Site {
  url: string
  label: string
  desc: string
  github?: string
  tags: string[]
  noEmbed?: boolean
  thumb?: string
  spec: SiteSpec
}

export const websites: Site[] = [
  {
    url: 'https://tlguide.com',
    label: 'tlguide.com',
    desc: 'I review Figma plugins and design tools. The reviews and the outreach run on AI, so the site mostly maintains itself. I built the whole thing with React, Hono and Drizzle on Cloudflare.',
    github: 'https://github.com/floridomeacci/TLguide',
    tags: ['Reviews', 'AI Pipeline', 'Full-stack'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#09090b' },
        secondary: { name: 'Secondary', hex: '#7c3aed' },
        tertiary: { name: 'Tertiary', hex: '#22c55e' },
        neutral: { name: 'Neutral', hex: '#f4f4f5' }
      },
      fonts: { headline: 'Space Grotesk', body: 'Inter', label: 'JetBrains Mono' },
      custom: { kind: 'search', placeholder: 'Search plugins…' }
    }
  },
  {
    url: 'https://www.figma.com/community/plugin/1626934504810261537',
    label: 'Filters & Grain',
    desc: 'A Figma plugin for color grading, film grain and vignette. One click gives you a curated set of filters and overlays, no Photoshop needed. I built it with React, Vite and Tailwind.',
    tags: ['Figma Plugin', 'Design Tool'],
    noEmbed: true,
    thumb: 'figma.webp',
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#f9b64f' },
        secondary: { name: 'Secondary', hex: '#141210' },
        tertiary: { name: 'Tertiary', hex: '#8a8580' },
        neutral: { name: 'Neutral', hex: '#030101' }
      },
      fonts: { headline: 'Onest', body: 'Onest', label: 'Onest' },
      custom: { kind: 'slider', label: 'Grain intensity' }
    }
  },
  {
    url: 'https://www.latentsearch.net/',
    label: 'latentsearch.net',
    desc: 'A search engine where every result is generated by AI on the spot. There is no index and nothing is real, every page is inferred by a Llama 4 Scout model running on Replicate.',
    github: 'https://github.com/floridomeacci/latentSearch',
    tags: ['AI', 'Search', 'Generative'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#dc2626' },
        secondary: { name: 'Secondary', hex: '#202124' },
        tertiary: { name: 'Tertiary', hex: '#1967d2' },
        neutral: { name: 'Neutral', hex: '#f1f3f4' }
      },
      fonts: { headline: 'Sora', body: 'Plus Jakarta Sans', label: 'JetBrains Mono' },
      custom: { kind: 'search', placeholder: 'Search the latent web' }
    }
  },
  {
    url: 'https://creditswap.app',
    label: 'creditswap.app',
    desc: 'A marketplace for trading AI API credits. Buyers pay less than retail, sellers get paid for capacity they would otherwise waste. I built the frontend in React and the routing and queueing on Cloudflare Workers.',
    github: 'https://github.com/floridomeacci/creditSwapV2',
    tags: ['Marketplace', 'AI', 'Fintech'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#111827' },
        secondary: { name: 'Secondary', hex: '#16a34a' },
        tertiary: { name: 'Tertiary', hex: '#030712' },
        neutral: { name: 'Neutral', hex: '#f9fafb' }
      },
      fonts: { headline: 'Inter', body: 'Inter', label: 'JetBrains Mono' },
      custom: { kind: 'swap', placeholder: 'Amount' }
    }
  },
  {
    url: 'https://reddituser.info',
    label: 'reddituser.info',
    desc: 'Paste a Reddit username and it turns their public activity into a full profile: interests, posting habits, the works, all generated by AI. I built it as a React dashboard with Tailwind.',
    github: 'https://github.com/floridomeacci/redditUserInfo',
    tags: ['AI', 'Analytics', 'React'],
    noEmbed: true,
    thumb: 'reddituserinfo.webp',
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#ff6b6b' },
        secondary: { name: 'Secondary', hex: '#4ade80' },
        tertiary: { name: 'Tertiary', hex: '#fb923c' },
        neutral: { name: 'Neutral', hex: '#1a1a1a' }
      },
      fonts: { headline: 'Space Grotesk', body: 'Space Grotesk', label: 'JetBrains Mono' },
      custom: { kind: 'input', placeholder: 'u/username' }
    }
  },
  {
    url: 'https://colino.work',
    label: 'colino.work',
    desc: 'An agent-native job search. Upload your CV and an AI agent filters live openings down to the roles that actually fit, instead of making you scroll through everything. I built it on WebMCP.',
    github: 'https://github.com/floridomeacci/colino',
    tags: ['AI', 'Jobs', 'WebMCP'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#008c11' },
        secondary: { name: 'Secondary', hex: '#cf630d' },
        tertiary: { name: 'Tertiary', hex: '#0e1216' },
        neutral: { name: 'Neutral', hex: '#f7f5f1' }
      },
      fonts: { headline: 'DM Serif Display', body: 'DM Sans', label: 'DM Sans' },
      custom: { kind: 'search', placeholder: 'Search jobs…' }
    }
  },
  {
    url: 'https://mlnpx.com',
    label: 'million.pixels',
    desc: 'A one-million-pixel canvas painted by AI agents, directed by whoever shows up. Each pixel is placed by an agent acting on a real prompt. I built it as a demo of WebMCP.',
    github: 'https://github.com/floridomeacci/mlnpx.webmcp',
    tags: ['AI Agents', 'WebMCP', 'Canvas'],
    noEmbed: true,
    thumb: 'millionpixels.webp',
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#f97316' },
        secondary: { name: 'Secondary', hex: '#22d3ee' },
        tertiary: { name: 'Tertiary', hex: '#08080c' },
        neutral: { name: 'Neutral', hex: '#ececf4' }
      },
      fonts: { headline: 'Sora', body: 'Plus Jakarta Sans', label: 'JetBrains Mono' },
      custom: { kind: 'swatches', label: 'Paint' }
    }
  }
]
