export interface PaletteColor {
  name: string
  hex: string
}

export type CustomKind = 'search' | 'slider' | 'input' | 'swap' | 'swatches'

export interface SiteSpec {
  palette: {
    primary: PaletteColor
    secondary: PaletteColor
    tertiary: PaletteColor
    neutral: PaletteColor
  }
  fonts: {
    headline: string
    body: string
    label: string
  }
  custom: {
    kind: CustomKind
    placeholder?: string
    label?: string
  }
}

export interface Site {
  url: string
  label: string
  desc: string
  github?: string
  tags: string[]
  stack: string[]
  noEmbed?: boolean
  thumb?: string
  spec: SiteSpec
}

export const websites: Site[] = [
  {
    url: 'https://tlguide.com',
    label: 'tlguide.com',
    desc: 'Independent reviews and guides for Figma plugins. I built the whole thing, and the reviews and outreach mostly run on AI.',
    github: 'https://github.com/floridomeacci/TLguide',
    tags: ['Reviews', 'AI Pipeline', 'Full-stack'],
    stack: ['React', 'Hono', 'Drizzle', 'Cloudflare', 'Tailwind'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#09090b' },
        secondary: { name: 'Secondary', hex: '#7c3aed' },
        tertiary: { name: 'Tertiary', hex: '#22c55e' },
        neutral: { name: 'Neutral', hex: '#f4f4f5' }
      },
      fonts: { headline: 'Space Grotesk', body: 'Inter', label: 'JetBrains Mono' },
      custom: { kind: 'search', placeholder: 'Search plugins…' }
    }
  },
  {
    url: 'https://www.figma.com/community/plugin/1626934504810261537',
    label: 'Filters & Grain',
    desc: 'A Figma plugin for color grading, film grain and vignette. No Photoshop needed.',
    tags: ['Figma Plugin', 'Design Tool'],
    stack: ['Figma Plugin', 'React', 'Vite', 'Tailwind'],
    noEmbed: true,
    thumb: 'figma.webp',
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#f9b64f' },
        secondary: { name: 'Secondary', hex: '#141210' },
        tertiary: { name: 'Tertiary', hex: '#8a8580' },
        neutral: { name: 'Neutral', hex: '#030101' }
      },
      fonts: { headline: 'Onest', body: 'Onest', label: 'Onest' },
      custom: { kind: 'slider', label: 'Grain intensity' }
    }
  },
  {
    url: 'https://www.latentsearch.net/',
    label: 'latentsearch.net',
    desc: 'A search engine where every result is generated by AI on the fly. Nothing is indexed, nothing is real.',
    github: 'https://github.com/floridomeacci/latentSearch',
    tags: ['AI', 'Search', 'Generative'],
    stack: ['HTML/CSS/JS', 'Llama 4 Scout', 'Replicate'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#dc2626' },
        secondary: { name: 'Secondary', hex: '#202124' },
        tertiary: { name: 'Tertiary', hex: '#1967d2' },
        neutral: { name: 'Neutral', hex: '#f1f3f4' }
      },
      fonts: { headline: 'Sora', body: 'Plus Jakarta Sans', label: 'JetBrains Mono' },
      custom: { kind: 'search', placeholder: 'Search the latent web' }
    }
  },
  {
    url: 'https://creditswap.app',
    label: 'creditswap.app',
    desc: 'A marketplace for reselling AI API credits. Buyers pay less, sellers get paid for capacity they do not use.',
    github: 'https://github.com/floridomeacci/creditSwapV2',
    tags: ['Marketplace', 'AI', 'Fintech'],
    stack: ['React', 'Vite', 'Tailwind', 'Cloudflare Workers'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#111827' },
        secondary: { name: 'Secondary', hex: '#16a34a' },
        tertiary: { name: 'Tertiary', hex: '#030712' },
        neutral: { name: 'Neutral', hex: '#f9fafb' }
      },
      fonts: { headline: 'Inter', body: 'Inter', label: 'JetBrains Mono' },
      custom: { kind: 'swap', placeholder: 'Amount' }
    }
  },
  {
    url: 'https://reddituser.info',
    label: 'reddituser.info',
    desc: 'Paste a Reddit username and get an AI report on their activity, interests and posting habits.',
    github: 'https://github.com/floridomeacci/redditUserInfo',
    tags: ['AI', 'Analytics', 'React'],
    stack: ['React', 'Vite', 'Tailwind', 'AI'],
    noEmbed: true,
    thumb: 'reddituserinfo.webp',
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#ff6b6b' },
        secondary: { name: 'Secondary', hex: '#4ade80' },
        tertiary: { name: 'Tertiary', hex: '#fb923c' },
        neutral: { name: 'Neutral', hex: '#1a1a1a' }
      },
      fonts: { headline: 'Space Grotesk', body: 'Space Grotesk', label: 'JetBrains Mono' },
      custom: { kind: 'input', placeholder: 'u/username' }
    }
  },
  {
    url: 'https://colino.work',
    label: 'colino.work',
    desc: 'An agent-native job search. Upload your CV and it filters live openings down to the roles that actually fit.',
    github: 'https://github.com/floridomeacci/colino',
    tags: ['AI', 'Jobs', 'WebMCP'],
    stack: ['WebMCP', 'AI', 'HTML/CSS/JS'],
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#008c11' },
        secondary: { name: 'Secondary', hex: '#cf630d' },
        tertiary: { name: 'Tertiary', hex: '#0e1216' },
        neutral: { name: 'Neutral', hex: '#f7f5f1' }
      },
      fonts: { headline: 'DM Serif Display', body: 'DM Sans', label: 'DM Sans' },
      custom: { kind: 'search', placeholder: 'Search jobs…' }
    }
  },
  {
    url: 'https://mlnpx.com',
    label: 'million.pixels',
    desc: 'A one-million-pixel canvas painted by AI agents and the people who direct them. A demo of WebMCP.',
    github: 'https://github.com/floridomeacci/mlnpx.webmcp',
    tags: ['AI Agents', 'WebMCP', 'Canvas'],
    stack: ['WebMCP', 'AI', 'HTML/CSS/JS'],
    noEmbed: true,
    thumb: 'millionpixels.webp',
    spec: {
      palette: {
        primary: { name: 'Primary', hex: '#f97316' },
        secondary: { name: 'Secondary', hex: '#22d3ee' },
        tertiary: { name: 'Tertiary', hex: '#08080c' },
        neutral: { name: 'Neutral', hex: '#ececf4' }
      },
      fonts: { headline: 'Sora', body: 'Plus Jakarta Sans', label: 'JetBrains Mono' },
      custom: { kind: 'swatches', label: 'Paint' }
    }
  }
]
